/* autogenerated by Processing revision 1313 on 2026-06-16 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class bubble_22 extends PApplet {

ArrayList<Ball> balls = new ArrayList<Ball>();
float gravityConstant = 0.5f;
float maxSpeed = 3.5f;

int lastSpawnTime = 0;
int spawnCooldown = 150;

public void setup() {
  /* size commented out by preprocessor */;
  for (int i = 0; i < 5; i++) {
    balls.add(new Ball(random(width), random(height)));
  }
}

public void draw() {
  background(0);

  // 1. 物理計算與壽命檢查（10秒消失）
  for (int i = balls.size() - 1; i >= 0; i--) {
    Ball b = balls.get(i);
    b.resetDeform();
    b.applyRepulsion(balls);
    b.applyMouseGravity();
    b.update();
    b.checkEdges();

    if (b.isDead()) {
      balls.remove(i);
    }
  }

  // 2. 視覺渲染：去光暈、純藍色單線條演算
  loadPixels();
  for (int x = 0; x < width; x++) {
    for (int y = 0; y < height; y++) {
      float sum = 0;

      for (Ball b : balls) {
        float dx = x - b.pos.x;
        float dy = y - b.pos.y;

        // 擠壓形狀扭曲變形
        float distortedX = dx * (1.0f + b.deform.x * 0.1f);
        float distortedY = dy * (1.0f + b.deform.y * 0.1f);

        float d = sqrt(distortedX * distortedX + distortedY * distortedY);
        sum += 100 * b.currentRadius / (d + 1);
      }

      float mouseD = dist(x, y, mouseX, mouseY);
      sum += 100 * 15 / (mouseD + 1);

      int index = x + y * width;

      // 【核心修改】精準過濾窄帶，只留單一純藍色實線邊框，其餘全部塗黑
      if (sum > 165 && sum < 180) {
        pixels[index] = color(0, 150, 255); // 乾淨亮藍色線條
      } else {
        pixels[index] = color(0, 0, 0);     // 內部與外部全純黑
      }
    }
  }
  updatePixels();
}

public void mouseDragged() {
  trySpawnBall();
}

public void mousePressed() {
  trySpawnBall();
}

public void trySpawnBall() {
  if (millis() - lastSpawnTime > spawnCooldown) {
    balls.add(new Ball(mouseX, mouseY));
    lastSpawnTime = millis();
  }
}

class Ball {
  PVector pos, vel, acc;
  PVector deform;
  float baseRadius;
  float currentRadius;
  int spawnTime;
  int lifetime = 10000;

  Ball(float startX, float startY) {
    pos = new PVector(startX, startY);
    vel = new PVector(random(-1.5f, 1.5f), random(-1.5f, 1.5f));
    acc = new PVector(0, 0);
    deform = new PVector(0, 0);

    baseRadius = random(8, 22);
    currentRadius = baseRadius;
    spawnTime = millis();
  }

  public void resetDeform() {
    deform.set(0, 0);
  }

  public void applyRepulsion(ArrayList<Ball> allBalls) {
    PVector steer = new PVector(0, 0);
    int count = 0;

    for (Ball other : allBalls) {
      if (other != this) {
        float d = PVector.dist(pos, other.pos);
        float minDist = (currentRadius + other.currentRadius) * 1.5f;

        if (d > 0 && d < minDist) {
          PVector diff = PVector.sub(pos, other.pos);
          diff.normalize();

          float overlap = minDist - d;
          diff.mult(overlap);
          steer.add(diff);

          deform.x += abs(diff.x);
          deform.y += abs(diff.y);
          count++;
        }
      }
    }

    if (count > 0) {
      steer.div((float)count);
      deform.div((float)count);
    }

    if (steer.mag() > 0) {
      steer.normalize();
      steer.mult(1.8f);
      acc.add(steer);
    }
  }

  public void applyMouseGravity() {
    PVector mousePos = new PVector(mouseX, mouseY);
    PVector force = PVector.sub(mousePos, pos);
    float distance = force.mag();
    distance = constrain(distance, 20.0f, 500.0f);
    force.normalize();
    float strength = (gravityConstant * currentRadius) / (distance * distance);
    force.mult(strength);
    acc.add(force);
  }

  public void update() {
    vel.add(acc);
    vel.limit(maxSpeed);
    pos.add(vel);
    acc.mult(0);

    int age = millis() - spawnTime;
    if (age < lifetime) {
      float lifeRatio = 1.0f - ((float)age / lifetime);
      currentRadius = baseRadius * lifeRatio;
    } else {
      currentRadius = 0;
    }
  }

  public boolean isDead() {
    return currentRadius <= 0;
  }

  public void checkEdges() {
    if (pos.x < 0 || pos.x > width) {
      vel.x *= -1;
      pos.x = constrain(pos.x, 0, width);
    }
    if (pos.y < 0 || pos.y > height) {
      vel.y *= -1;
      pos.y = constrain(pos.y, 0, height);
    }
  }
}


  public void settings() { size(600, 400); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "--full-screen", "--bgcolor=#666666", "--stop-color=#cccccc", "bubble_22" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
